- name: Config DNS server
  hosts: centos7
  remote_user: billy

  tasks:
  - name: install packages
    yum:
      name:
        - bind
        - chrony
        - vsftpd
        - ftp
        - epel-release
      state: latest
    become: yes   

  - name: disable SELinux
    ansible.builtin.replace:
      path: /etc/sysconfig/selinux
      regexp: 'SELINUX=enforcing'
      replace: 'SELINUX=disabled'

  - name: edit ssh pw authentication
    ansible.builtin.replace:
      path: /etc/ssh/sshd_config
      regexp: '#PasswordAuthentication yes'
      replace: 'PasswordAuthentication yes'     
    become: yes   

  - name: edit ssh authentication
    ansible.builtin.replace:
      path: /etc/ssh/sshd_config
      regexp: '#PermitRootLogin yes'
      replace: 'PermitRootLogin yes'
    become: yes

  - name: reload ssh
    command: systemctl restart sshd  
    become: yes

  - name: add dns rule permanently
    firewalld:
      service: dns
      permanent: yes
      state: enabled
    become: yes

  - name: add port 53 tcp/udp
    firewalld:
      port: "{{ item }}"
      permanent: yes
      state: enabled
    loop:
      - 53/tcp
      - 53/udp
    become: yes

  - name: add tcp service
    firewalld:
      service: ftp
      permanent: yes
      state: enabled
    become: yes

  - name: add port 21
    firewalld:
      port: 21/tcp
      permanent: yes
      state: enabled
    become: yes
  
  - name: reload firewall
    command: firewall-cmd --reload
    become: yes
    
  - name: replace ip of DNS allow-list
    ansible.builtin.replace:
      path: /etc/named.conf
      regexp: '103.82.116.0/24'
      replace: '103.82.116.0/22'
    become: yes
