- name: Config DNS server
  hosts: centos7
  remote_user: root

  tasks:
  - name: edit security options in /etc/named.conf
    ansible.builtin.yum:
      name: bind
      state: latest

  - name: install epel-release
    yum:
      name: epel-release
      state: latest

  - name: add DNS service to firewall
    command: firewall-cmd --permanent --add-service=dns
  
  - name: reload firewall
    command: firewall-cmd --reload
    
  - name: replace ip of DNS allow-list
    ansible.builtin.replace:
      path: /etc/named.conf
      regexp: '103.82.116.0/24'
      replace: '103.82.116.0/22'

